# Generated by Django 5.2.2 on 2025-06-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="项目标题")),
                ("name", models.CharField(max_length=200, verbose_name="项目名称")),
                ("summary", models.TextField(verbose_name="项目描述")),
                ("is_hot", models.BooleanField(default=False, verbose_name="是否热门")),
                (
                    "is_claimed",
                    models.BooleanField(default=False, verbose_name="是否认领"),
                ),
                (
                    "clicks_total",
                    models.IntegerField(default=0, verbose_name="点击总数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "GitHub项目",
                "verbose_name_plural": "GitHub项目",
                "ordering": ["-clicks_total"],
            },
        ),
    ]
