# Generated by Django 5.2.2 on 2025-06-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubproject",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="评论内容"),
        ),
        migrations.AddField(
            model_name="githubproject",
            name="item_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="项目ID"
            ),
        ),
    ]
